services:
  planka:
    image: ghcr.io/plankanban/planka:latest
    container_name: prod_araucaria_plankanban
    ports:
      - "1337:1337"
    environment:
      - PUID=1000
      - PGID=1000    
      - TZ=America/Sao_Paulo
      # - DATABASE_URL=postgres://planka:planka@pgvector:5432/planka
      - DATABASE_URL=postgres://planka:planka@prod_araucaria_postgres:5432/planka
      - SECRET_KEY=uma_senha_bem_forte
      - TRUST_PROXY=1
      - DEFAULT_ADMIN_EMAIL=smcit@araucaria.pr.gov.br
      - DEFAULT_ADMIN_USERNAME=smcit
      - DEFAULT_ADMIN_PASSWORD=smcit
      - "DEFAULT_ADMIN_NAME=SMCIT Projects"   
      # - BASE_URL=https://planka.example.com
      - BASE_URL=http://192.168.101.126:1337
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:1337"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: always
    networks:
      # - pgvector_net
      - araucaria

networks:
  # pgvector_net:
  araucaria:
    external: true
  